apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../../../templates/windows-pr.yaml
patches:
- path: ../patches/vnet-peering.yaml
- path: ../patches/machine-identity.yaml
