apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  annotations:
    runtime: containerd
  name: ${CLUSTER_NAME}-md-win
  namespace: default
spec:
  template:
    spec:
      image:
        marketplace:
          offer: capi-windows
          publisher: cncf-upstream
          sku: ${IMAGE_SKU:=windows-2019-containerd-gen1}
          version: ${IMAGE_VERSION:="latest"}
